env:
  browser: false
  es2021: true
extends:
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 13
  sourceType: module
rules: {
  "no-console": ["off", "always"],
  "import/extensions": ["off", "always"]
}
